### ISSUE TITLE
Password with "#" causing error

### ISSUE THREAD

**Issue by steelheaddigital** [IBM-Cloud/redli#10]
When I have a password with a "#" character in it, the connection fails with the error:

`Dial dial tcp: lookup tcp/'w6: getaddrinfow: The specified class was not found.`

Other special characters seem OK. This is on Windows 10.

**Comment by ullumullu** [comment]
Thanks. This will be fixed with the next release! It's related to #9

**Comment by ullumullu** [comment]
PR: https://github.com/IBM-Cloud/redli/pull/12

Fixed in Release: https://github.com/IBM-Cloud/redli/releases/tag/v0.4.4
