### ISSUE TITLE
Set notify-keyspace-events Ex

### ISSUE THREAD

**Issue by sabuhish** [IBM-Cloud/redli#16]
Hi there!

We are implemenitng redis database offered by Digitalocean. Currently having troubleshooting on configuring the database. We are aware that redis does not support SSL/TLS support therefore digital ocean offers us to coonect redis-database with redli not with redis-cli whereas redli supports connection with TLS. 

Our team used some configuration for redis as follows below:
config set notify-keyspace-events Ex

With redli we are not able have this feautures, indeed we should set this config. 
We are able to connect to database for project we should set this config, unfortunately redli does not support set this config.

What we tried:
We could not connect to server where database is set.
Thought may be stunnel, but not solution for this issue.

Any possibilities to connect redis database with redis-cli or any solution for setting this conf on the server side or any way to set this config on redli?

**Comment by ullumullu** [comment]
Hey @sabuhish `config set` commands should be supported via Redli.

Is there a specific error message shown when you try to do execute the command via Redli? 

Also did you use the interactive mode or have you added the command as arguments to Redli?

**Comment by prashb94** [comment]
Most cloud providers that provide managed redis as a service block access to config commands (Example: DigitalOcean) I'd be interested in knowing if there's a workaround to enable keyspace notifications on DigitalOcean managed redis for example.

**Comment by ullumullu** [comment]
>  I'd be interested in knowing if there's a workaround to enable keyspace notifications on DigitalOcean managed redis for example.

That's not really in scope for redli I assume. Best answered by digitalocean.

```
> config set notify-keyspace-events Ex
OK
```
