### ISSUE TITLE
Is the monitor command broken?

### ISSUE THREAD

**Issue by cameronspeakflash** [IBM-Cloud/redli#20]
Ping works but monitor doesn't:

> ping
PONG
> monitor
(error) ERR unknown command `monitor`, with args beginning with: 

Is it because monitor takes no arguments?

**Comment by codepope** [comment]
I think more because it was never implemented as it switches to a pure streaming mode, one not supported by the client as I recall.

https://redis.io/commands/monitor - offers a workaround of using telnet and issuing the raw command there.

**Comment by ullumullu** [comment]
Release 0.4.5 should contain a fix for the monitoring issue 🎉
