### ISSUE TITLE
-n flag is not taking effect (?)

### ISSUE THREAD

**Issue by oren1991** [IBM-Cloud/redli#33]
I am trying to use redli in the command line, and I realized and it does not recognize my -n flag.

```bash
>redli -u <myurl> -n 1 set hello world
OK
>redli -u <myurl>
Connected to 5.0.5
>select 1
OK
>get hello
nil
>select 0
OK
>get hello
"world"
```
I would expect nil to be "world" as I was setting the key for "-n 1". As I am swithcing back to db 0 the key is set up there. Is there something I am doing wrong?

Thank you!

**Comment by ullumullu** [comment]
Hey so redli does support the `-n` flag. However not in "mixed" mode when using a uri. For now you can achieve the behaviour you like by adding the keyspace you want to use at the end of the uri.

E.g.: `rediss://admin:secret@redis.local:6379/1`

**Comment by oren1991** [comment]
I see thank you verymuch!!
