### ISSUE TITLE
Support for aarch64 architecture

### ISSUE THREAD

**Issue by alejandrotoga02** [IBM-Cloud/redli#47]
It would be nice to have support for Mac M1 chips

**Comment by sudomateo** [comment]
Agreed. This would be great!

**Comment by jimlindeman** [comment]
https://goreleaser.com/customization/builds/  shows examples supporting arm64 as a target arch, so you should be able to just update the .goreleaser.yaml at https://github.com/IBM-Cloud/redli/blob/master/.goreleaser.yml#L13
just add a 
``` 
    - arm64 
```
