### ISSUE TITLE
passing "dash" argument

### ISSUE THREAD

**Issue by jgranduel** [IBM-Cloud/redli#8]
Hi, 

thanks for this project (specially for someone being on Windows).
Small question : how do you properly escape dash parameters?
like in
>redli.exe xrange - +
>redli.exe: error: unknown short flag '-', try --help

Thanks

**Comment by ullumullu** [comment]
@jgranduel try `redli xrange -- somestream - +`

This works on the unix-shell on Mac. Currently I don't have access to a Windows machine - so let me know if that works!

**Comment by jgranduel** [comment]
Hi, 

thanks very much for your answer.
Indeed it works fine on my Win10-1809, with PowerShell-5.1, PowerShell Core and cmd.exe !
Would you mind include this tip in the help?
Best regards

**Comment by jgranduel** [comment]
By mistake, I have also seen that ```redli xrange somestream -- - +``` also works.

**Comment by ullumullu** [comment]
> More precisely, a double dash (--) is used in bash built-in commands and many other commands to signify the end of command options, after which only positional parameters are accepted.
