### ISSUE TITLE
Passing password with forward slash causing URL analysis failed to connect

### ISSUE THREAD

**Issue by kasim** [IBM-Cloud/redli#9]
Hi there,

Thank you for this project so that I could connecting to TLS enabled REDIS without stunnel (https://www.stunnel.org/)

However, I found that with the arguments '--tls' and '-a' where there are characters '/' in the password value cause problem to connect my target REDIS server. 

After I read the source code, I found the problem is from redis.go of this project which passes connectionurl to conn.go from gomodule/redigo. And finally, I found in line 270 of conn.go in gomodule/redigo using 'host, port, err := net.SplitHostPort(u.Host)' parses wrongly the host and port if the password in the connectionurl in it with '/'.

For my personal usage, I already changed in my local of redis.go of this project to use redis.Dial(...) as following:

conn, err = redis.Dial('tcp', address, redis.DialPassword(*redisauth), redis.DialUseTLS(*redistls))

I don't know is it a proper solution on this project level, if it's not, please correct me. And could the owner of this project to update this so that anyone facing this problem could get an official solution?

Thanks and best regards.

**Comment by ullumullu** [comment]
Thanks for your feedback. This will be fixed with the next release!

**Comment by ullumullu** [comment]
PR: #12

Fixed in Release: https://github.com/IBM-Cloud/redli/releases/tag/v0.4.4
